services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build: ./frontend
    environment:
      - BACKEND_URL=http://web:8000
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    command: streamlit run Home.py --server.port 8501 --server.address 0.0.0.0

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auditdb
